const fs = require('fs');

let jsx = fs.readFileSync('src/pages/ReportView.jsx', 'utf8');

// Import ReportTemplate
jsx = "import ReportTemplate from '../components/ReportTemplate';\n" + jsx;

// Replace reportHtml state with reportData
jsx = jsx.replace(/const \[reportHtml, setReportHtml\] = useState\(null\);/g, "const [reportData, setReportData] = useState(null);");
jsx = jsx.replace(/const html = await VinService\.getReport\(vin\);/g, "const data = await VinService.getReport(vin);");
jsx = jsx.replace(/setReportHtml\(html\);/g, "setReportData(data);");

// Replace rendering
const oldRender = `{/* Report Content */}
            <div className="report-container">
                <div className="report-paper">
                    {/* Header Logo */}
                    <div className="report-header-logo">
                        <img src={logo} alt="Carkasa Logo" className="report-logo" />
                    </div>

                    <div className="report-content">
                        <div dangerouslySetInnerHTML={{ __html: reportHtml }} />
                    </div>

                    {/* Footer Logo */}
                    <div className="report-footer-logo">
                        <img src={logo} alt="Carkasa Logo" className="report-logo-small" />
                        <p className="footer-text">Generated by Carkasa - The Trusted Vehicle History Provider</p>
                        <p className="footer-subtext">{new Date().toLocaleDateString()}</p>
                    </div>
                </div>
            </div>`;

const newRender = `{/* Report Content */}
            {reportData && <ReportTemplate data={reportData.data || reportData} />}`;

jsx = jsx.replace(oldRender, newRender);

fs.writeFileSync('src/pages/ReportView.jsx', jsx);
console.log('ReportView updated successfully');
