import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Printer } from 'lucide-react';
import { VinService } from '../services/VinService';
import ReportTemplate from '../components/ReportTemplate';
import ReportLoader from '../components/Common/ReportLoader';
import './ReportView.css';

import logo from '../assets/logo-new.png';

const ReportView = () => {
    const { vin } = useParams();
    const navigate = useNavigate();
    const [reportData, setReportData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchReport = async () => {
            try {
                setLoading(true);
                const result = await VinService.getReport(vin);
                setReportData(result);
            } catch (err) {
                console.error("Failed to load report", err);
                setError(err.message || "Failed to load report data. Please try again.");
            } finally {
                setLoading(false);
            }
        };

        if (vin) {
            fetchReport();
        }
    }, [vin]);

    const handlePrint = () => {
        window.print();
    };

    const [count, setCount] = useState(1);

    useEffect(() => {
        if (loading) {
            const timer = setInterval(() => {
                setCount((prev) => {
                    if (prev >= 5) {
                        clearInterval(timer);
                        return 5;
                    }
                    return prev + 1;
                });
            }, 800); // Update every 800ms to reach 5 in ~4 seconds
            return () => clearInterval(timer);
        }
    }, [loading]);

    if (loading) {
        return <ReportLoader count={count} />;
    }

    if (error) {
        return (
            <div className="report-view-page" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', color: '#ef4444' }}>
                <p style={{ fontSize: '1.25rem', marginBottom: '1rem' }}>{error}</p>
                <button onClick={() => navigate('/member')} style={{ color: '#1e40af', textDecoration: 'none', background: 'none', border: 'none', cursor: 'pointer' }}>
                    Return to Dashboard
                </button>
            </div>
        );
    }

    return (
        <div className="report-view-page">
            {/* Header Toolbar */}
            <div className="report-toolbar no-print">
                <div className="toolbar-content">
                    <button
                        onClick={() => navigate('/member')}
                        className="back-btn"
                    >
                        <ArrowLeft size={20} />
                        Back to Dashboard
                    </button>

                    <div className="toolbar-actions">
                        <button onClick={handlePrint} className="action-btn">
                            <Printer size={20} />
                            <span className="action-text">Print</span>
                        </button>
                    </div>
                </div>
            </div>

            {/* Print Warning Note */}
            <div className="no-print" style={{
                backgroundColor: '#fff3cd',
                color: '#856404',
                padding: '1rem',
                textAlign: 'center',
                marginBottom: '1rem',
                border: '1px solid #ffeeba',
                borderRadius: '4px',
                margin: '1rem auto',
                maxWidth: '800px'
            }}>
                <strong>Please remember to save the report by selecting 'Print'.</strong> This is a one-time instant report and cannot be retrieved later.
            </div>

            {/* Report Content */}
            <div className="report-container">
                <div className="report-paper">
                    {/* Header Logo removed because ReportTemplate provides its own */}

                    <div className="report-content" style={{ padding: '0' }}>
                        {reportData?.type === 'html' ? (
                            <div dangerouslySetInnerHTML={{ __html: reportData.data }} style={{ padding: '2rem' }} />
                        ) : (
                            <ReportTemplate data={reportData?.data?.report || reportData?.data?.data || reportData?.data} />
                        )}
                    </div>

                    {/* Footer Logo */}
                    <div className="report-footer-logo">
                        <img src={logo} alt="Vehicle Report Check Logo" className="report-logo-small" />
                        <p className="footer-text">Generated by Vehicle Report Check - The Trusted Vehicle History Provider</p>
                        <p className="footer-subtext">{new Date().toLocaleDateString()}</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ReportView;
